<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Plant;

class SimplePlantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear existing plants
        Plant::query()->delete();

        $plants = [
            [
                'name' => 'Monstera Deliciosa',
                'description' => 'Popular indoor plant with beautiful split leaves. Easy to care for and grows well indoors. Perfect for adding tropical vibes to any space.',
                'price' => 89.99,
                'stock_count' => 15,
                'category' => 'indoor',
                'plant_type' => 'plant',
                'environment' => 'indoor',
                'image' => 'monstera.jpg',
                'is_seasonal' => false,
                'season' => null,
            ],
            [
                'name' => 'Snake Plant',
                'description' => 'Hardy indoor plant that purifies air. Perfect for beginners and low-light conditions. Virtually indestructible.',
                'price' => 34.99,
                'stock_count' => 30,
                'category' => 'indoor',
                'plant_type' => 'plant',
                'environment' => 'indoor',
                'image' => 'snake-plant.jpg',
                'is_seasonal' => false,
                'season' => null,
            ],
            [
                'name' => 'Pothos',
                'description' => 'Trailing vine plant with heart-shaped leaves. Excellent for hanging baskets and easy propagation.',
                'price' => 24.99,
                'stock_count' => 45,
                'category' => 'indoor',
                'plant_type' => 'plant',
                'environment' => 'indoor',
                'image' => 'pothos.jpg',
                'is_seasonal' => false,
                'season' => null,
            ],
            [
                'name' => 'Peace Lily',
                'description' => 'Elegant white flowers and glossy leaves. Great air purifier and thrives in low light conditions.',
                'price' => 42.99,
                'stock_count' => 25,
                'category' => 'indoor',
                'plant_type' => 'flowering',
                'environment' => 'indoor',
                'image' => 'peace-lily.jpg',
                'is_seasonal' => false,
                'season' => null,
            ],
            [
                'name' => 'Aloe Vera',
                'description' => 'Medicinal succulent known for its healing properties. Easy to care for indoors with many benefits.',
                'price' => 22.99,
                'stock_count' => 40,
                'category' => 'succulents',
                'plant_type' => 'succulent',
                'environment' => 'indoor',
                'image' => 'aloe-vera.jpg',
                'is_seasonal' => false,
                'season' => null,
            ],
            [
                'name' => 'Echeveria',
                'description' => 'Beautiful rosette-shaped succulent with fleshy leaves. Perfect for sunny windowsills.',
                'price' => 18.99,
                'stock_count' => 60,
                'category' => 'succulents',
                'plant_type' => 'succulent',
                'environment' => 'indoor',
                'image' => 'echeveria.jpg',
                'is_seasonal' => false,
                'season' => null,
            ],
            [
                'name' => 'Jade Plant',
                'description' => 'Classic succulent with thick, glossy leaves. Symbol of prosperity and very easy to care for.',
                'price' => 28.99,
                'stock_count' => 35,
                'category' => 'succulents',
                'plant_type' => 'succulent',
                'environment' => 'indoor',
                'image' => 'jade-plant.jpg',
                'is_seasonal' => false,
                'season' => null,
            ],
            [
                'name' => 'Fiddle Leaf Fig',
                'description' => 'Trendy indoor plant with large, violin-shaped leaves. Statement piece for modern interiors.',
                'price' => 125.99,
                'stock_count' => 12,
                'category' => 'indoor',
                'plant_type' => 'plant',
                'environment' => 'indoor',
                'image' => 'fiddle-leaf-fig.jpg',
                'is_seasonal' => false,
                'season' => null,
            ],
            [
                'name' => 'Rubber Plant',
                'description' => 'Glossy, dark green leaves and easy care. Excellent air purifier for home and office.',
                'price' => 55.99,
                'stock_count' => 20,
                'category' => 'indoor',
                'plant_type' => 'plant',
                'environment' => 'indoor',
                'image' => 'rubber-plant.jpg',
                'is_seasonal' => false,
                'season' => null,
            ],
            [
                'name' => 'ZZ Plant',
                'description' => 'Extremely tolerant plant with waxy, dark green leaves. Perfect for forgetful plant owners.',
                'price' => 38.99,
                'stock_count' => 28,
                'category' => 'indoor',
                'plant_type' => 'plant',
                'environment' => 'indoor',
                'image' => 'zz-plant.jpg',
                'is_seasonal' => false,
                'season' => null,
            ],
            [
                'name' => 'English Ivy',
                'description' => 'Classic climbing vine with elegant leaves. Great for indoor hanging baskets.',
                'price' => 19.99,
                'stock_count' => 50,
                'category' => 'indoor',
                'plant_type' => 'plant',
                'environment' => 'indoor',
                'image' => 'english-ivy.jpg',
                'is_seasonal' => false,
                'season' => null,
            ],
            [
                'name' => 'Spider Plant',
                'description' => 'Arching leaves with baby plantlets. Excellent air purifier and very easy to propagate.',
                'price' => 16.99,
                'stock_count' => 55,
                'category' => 'indoor',
                'plant_type' => 'plant',
                'environment' => 'indoor',
                'image' => 'spider-plant.jpg',
                'is_seasonal' => false,
                'season' => null,
            ],
            [
                'name' => 'Boston Fern',
                'description' => 'Lush, feathery fronds that add humidity to indoor spaces. Perfect for bathrooms.',
                'price' => 32.99,
                'stock_count' => 22,
                'category' => 'indoor',
                'plant_type' => 'plant',
                'environment' => 'indoor',
                'image' => 'boston-fern.jpg',
                'is_seasonal' => false,
                'season' => null,
            ],
            [
                'name' => 'Bird of Paradise',
                'description' => 'Exotic plant with banana-like leaves and orange-blue flowers. Tropical statement piece.',
                'price' => 95.99,
                'stock_count' => 10,
                'category' => 'indoor',
                'plant_type' => 'flowering',
                'environment' => 'indoor',
                'image' => 'bird-of-paradise.jpg',
                'is_seasonal' => false,
                'season' => null,
            ],
            [
                'name' => 'Dracaena',
                'description' => 'Tall, dramatic plant with strappy leaves. Great for adding height to indoor spaces.',
                'price' => 48.99,
                'stock_count' => 18,
                'category' => 'indoor',
                'plant_type' => 'plant',
                'environment' => 'indoor',
                'image' => 'dracaena.jpg',
                'is_seasonal' => false,
                'season' => null,
            ],
            [
                'name' => 'Philodendron',
                'description' => 'Heart-shaped leaves and easy care. Popular choice for indoor plant enthusiasts.',
                'price' => 36.99,
                'stock_count' => 33,
                'category' => 'indoor',
                'plant_type' => 'plant',
                'environment' => 'indoor',
                'image' => 'philodendron.jpg',
                'is_seasonal' => false,
                'season' => null,
            ],
            [
                'name' => 'Succulent Mix',
                'description' => 'Assorted collection of colorful succulents. Perfect for creating mini gardens.',
                'price' => 45.99,
                'stock_count' => 40,
                'category' => 'succulents',
                'plant_type' => 'succulent',
                'environment' => 'indoor',
                'image' => 'succulent-mix.jpg',
                'is_seasonal' => false,
                'season' => null,
            ],
            [
                'name' => 'Orchid',
                'description' => 'Elegant flowering plant with exotic blooms. Perfect for special occasions and home decor.',
                'price' => 68.99,
                'stock_count' => 15,
                'category' => 'flowering',
                'plant_type' => 'flowering',
                'environment' => 'indoor',
                'image' => 'orchid.jpg',
                'is_seasonal' => false,
                'season' => null,
            ],
            [
                'name' => 'Bamboo Palm',
                'description' => 'Graceful palm with feathery fronds. Great for adding tropical feel to any room.',
                'price' => 52.99,
                'stock_count' => 20,
                'category' => 'indoor',
                'plant_type' => 'plant',
                'environment' => 'indoor',
                'image' => 'bamboo-palm.jpg',
                'is_seasonal' => false,
                'season' => null,
            ],
            [
                'name' => 'Tropical Palm',
                'description' => 'Exotic palm tree that brings tropical vibes to any space. Perfect for large rooms.',
                'price' => 78.99,
                'stock_count' => 8,
                'category' => 'indoor',
                'plant_type' => 'plant',
                'environment' => 'indoor',
                'image' => 'tropical-palm.jpg',
                'is_seasonal' => false,
                'season' => null,
            ],
            [
                'name' => 'Desert Cactus',
                'description' => 'Hardy cactus perfect for dry conditions. Minimal water requirements and unique appearance.',
                'price' => 25.99,
                'stock_count' => 45,
                'category' => 'succulents',
                'plant_type' => 'succulent',
                'environment' => 'outdoor',
                'image' => 'desert-cactus.jpg',
                'is_seasonal' => false,
                'season' => null,
            ],
            [
                'name' => 'Garden Rose',
                'description' => 'Classic beauty with fragrant blooms. Perfect for gardens and special occasions.',
                'price' => 45.99,
                'stock_count' => 30,
                'category' => 'flowers',
                'plant_type' => 'flowering',
                'environment' => 'outdoor',
                'image' => 'garden-rose.jpg',
                'is_seasonal' => true,
                'season' => 'summer',
            ],
            [
                'name' => 'Herbal Basil',
                'description' => 'Aromatic herb essential for cooking. Easy to grow in pots or gardens with fresh flavor.',
                'price' => 12.99,
                'stock_count' => 60,
                'category' => 'herbs',
                'plant_type' => 'herb',
                'environment' => 'outdoor',
                'image' => 'herbal-basil.jpg',
                'is_seasonal' => false,
                'season' => null,
            ],
            [
                'name' => 'Fern Collection',
                'description' => 'Various ferns perfect for shady spots. Lush green foliage that adds life to any space.',
                'price' => 35.99,
                'stock_count' => 25,
                'category' => 'foliage',
                'plant_type' => 'foliage',
                'environment' => 'indoor',
                'image' => 'fern-collection.jpg',
                'is_seasonal' => false,
                'season' => null,
            ],
            [
                'name' => 'Bonsai Tree',
                'description' => 'Miniature tree perfect for meditation and decoration. Living art that requires care and patience.',
                'price' => 95.99,
                'stock_count' => 5,
                'category' => 'trees',
                'plant_type' => 'tree',
                'environment' => 'indoor',
                'image' => 'bonsai-tree.jpg',
                'is_seasonal' => false,
                'season' => null,
            ],
        ];

        foreach ($plants as $plant) {
            Plant::create($plant);
        }

        echo "Seeded " . count($plants) . " plants with images!\n";
    }
}
